name: Make Build

on:
  push:
    branches:
      - main
      - release
  workflow_dispatch:

jobs:
  make:
    name: Make (${{ matrix.label }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            label: macOS
          - os: windows-latest
            label: Windows
    env:
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run make
        run: pnpm run make

      - name: Upload make artifacts
        uses: actions/upload-artifact@v4
        with:
          name: make-${{ matrix.label }}
          path: apps/electron/out/make
          if-no-files-found: error
